#!/bin/bash -e

# To test, run
# nextflow run nf-core/rnaseq -profile test,singularity --outdir /scratch/karcher/an_outdir_lul -c ~/nextflow.confi

mkdir -p ../results/nfcore_rnaseq/; conda activate /g/scb2/zeller/karcher/mambaforge/envs/nextflow; cd ../data/rnaseq_reads_proper_names_softlinks/;  nextflow run nf-core/rnaseq -profile singularity --outdir ../../results/nfcore_rnaseq/C_secundus_DSM28864 -c ~/nextflow.confi --input ../../scripts/Csecundus_samplesheet.csv --fasta ../genomes/C_secundus_DSM28864.fna --gtf ../../results/prokka/C_secundus_DSM28864/C_secundus_DSM28864.gtf --skip_gtf_transcript_filter  --skip_dupradar --save_align_intermeds; cd ../../scripts

mkdir -p ../results/nfcore_rnaseq/; conda activate /g/scb2/zeller/karcher/mambaforge/envs/nextflow; cd ../data/rnaseq_reads_proper_names_softlinks/;  nextflow run nf-core/rnaseq -w /scratch/karcher/a -with-timeline timeline_a -profile singularity --outdir ../../results/nfcore_rnaseq/P_vulgatus_atcc8482nt5001 -c ~/nextflow.confi --input ../../scripts/Pvulgatus_samplesheet.csv --fasta ../genomes/P_vulgatus_atcc8482nt5001.fna --gtf ../../results/prokka/P_vulgatus_atcc8482nt5001/P_vulgatus_atcc8482nt5001.gtf --skip_gtf_transcript_filter  --skip_dupradar --save_align_intermeds; cd ../../scripts

mkdir -p ../results/nfcore_rnaseq/; conda activate /g/scb2/zeller/karcher/mambaforge/envs/nextflow; cd ../data/rnaseq_reads_proper_names_softlinks/;  nextflow run nf-core/rnaseq -w /scratch/karcher/b -with-timeline timeline_b -profile singularity --outdir ../../results/nfcore_rnaseq/B_uniformis_atcc8492nt5002 -c ~/nextflow.confi --input ../../scripts/Buniformis_samplesheet.csv --fasta ../genomes/B_uniformis_atcc8492nt5002.fna --gtf ../../results/prokka/B_uniformis_atcc8492nt5002/B_uniformis_atcc8492nt5002.gtf --skip_gtf_transcript_filter  --skip_dupradar --save_align_intermeds; cd ../../scripts

mkdir -p ../results/nfcore_rnaseq/; conda activate /g/scb2/zeller/karcher/mambaforge/envs/nextflow; cd ../data/rnaseq_reads_proper_names_softlinks/;  nextflow run nf-core/rnaseq -w /scratch/karcher/c -with-timeline timeline_c -profile singularity --outdir ../../results/nfcore_rnaseq/H_hathewayi_DSM13479 -c ~/nextflow.confi --input ../../scripts/Hhathewayi_samplesheet.csv --fasta ../genomes/H_hathewayi_DSM13479.fna --gtf ../../results/prokka/H_hathewayi_DSM13479/H_hathewayi_DSM13479.gtf --skip_gtf_transcript_filter  --skip_dupradar --save_align_intermeds; cd ../../scripts

mkdir -p ../results/nfcore_rnaseq/; conda activate /g/scb2/zeller/karcher/mambaforge/envs/nextflow; cd ../data/rnaseq_reads_proper_names_softlinks/;  nextflow run nf-core/rnaseq -w /scratch/karcher/d -with-timeline timeline_d -profile singularity --outdir ../../results/nfcore_rnaseq/E_tayi_DSM26961 -c ~/nextflow.confi --input ../../scripts/Etayi_samplesheet.csv --fasta ../genomes/E_tayi_DSM26961.fna --gtf ../../results/prokka/E_tayi_DSM26961/E_tayi_DSM26961.gtf --skip_gtf_transcript_filter  --skip_dupradar --save_align_intermeds; cd ../../scripts
